version: "3"

services:
  metrito:
    container_name: metritoapp
    build: .
    command: yarn dev
    ports:
      - "80:80"
    volumes:
      - .:/usr/app
    environment:
      - NODE_ENV=development
